# Generated by Django 3.1.6 on 2021-02-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('manufacturer', models.CharField(max_length=250)),
                ('carrier', models.CharField(max_length=250)),
                ('review', models.TextField(max_length=250)),
            ],
        ),
    ]
