# Generated by Django 3.1.6 on 2021-02-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='usage date')),
                ('usage', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], default='M', max_length=1)),
                ('time', models.CharField(max_length=1)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.phone')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
